/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWorkRouteImport } from './routes/_app/work'
import { Route as AppSportRouteImport } from './routes/_app/sport'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNutritionRouteImport } from './routes/_app/nutrition'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)
const AppSportRoute = AppSportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/finance': typeof AppFinanceRoute
  '/nutrition': typeof AppNutritionRoute
  '/settings': typeof AppSettingsRoute
  '/sport': typeof AppSportRoute
  '/work': typeof AppWorkRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/finance': typeof AppFinanceRoute
  '/nutrition': typeof AppNutritionRoute
  '/settings': typeof AppSettingsRoute
  '/sport': typeof AppSportRoute
  '/work': typeof AppWorkRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sport': typeof AppSportRoute
  '/_app/work': typeof AppWorkRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/finance'
    | '/nutrition'
    | '/settings'
    | '/sport'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/finance'
    | '/nutrition'
    | '/settings'
    | '/sport'
    | '/work'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/finance'
    | '/_app/nutrition'
    | '/_app/settings'
    | '/_app/sport'
    | '/_app/work'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sport': {
      id: '/_app/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof AppSportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFinanceRoute: typeof AppFinanceRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSportRoute: typeof AppSportRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFinanceRoute: AppFinanceRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSportRoute: AppSportRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
